// src/frontend/domonow-angular-parking/src/app/app.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ParkingStateService } from './services/parking.service';
import { ParkingGridComponent } from './components/parking-grid.component';
import { EntryModalComponent } from './components/entry-modal.component';
import { CheckoutModalComponent } from './components/checkout-modal.component';

@Component({
  selector: 'app-domonow-angular-parking',
  standalone: true,
  imports: [CommonModule, ParkingGridComponent, EntryModalComponent, CheckoutModalComponent],
  template: `
    <div class="mfe-container">
      <!-- Subproject Visual Header -->
      <header class="mfe-header">
        <div class="header-left">
          <div class="brand-pill">
            <span class="brand-sub">OPERACIONES EN VIVO</span>
          </div>
          <h2>Control de Parqueadero de Visitantes</h2>
          <p class="subtitle">Monitoreo y asignación en tiempo real para portería y guardias de seguridad</p>
        </div>

        <div class="header-right">
          <button
            class="concurrency-btn"
            (click)="state.simulateConcurrencyRace('P-15')"
            title="Prueba de esfuerzo con 10 requests concurrentes simultáneos"
          >
            ⚡ Simular Ráfaga Concurrente (P-15)
          </button>
        </div>
      </header>

      <!-- Concurrency Test Live Notification -->
      <div *ngIf="state.concurrencyNotice()" class="concurrency-alert">
        <span class="alert-icon">🛡️</span>
        <span class="alert-text">{{ state.concurrencyNotice() }}</span>
      </div>

      <!-- KPI Summary Cards -->
      <div class="kpi-grid">
        <div class="kpi-card total">
          <span class="kpi-title">Total Cupos</span>
          <span class="kpi-value">{{ state.stats().totalSpots }}</span>
          <span class="kpi-tag">Capacidad Máxima</span>
        </div>

        <div class="kpi-card available">
          <span class="kpi-title">Disponibles</span>
          <span class="kpi-value">{{ state.stats().availableSpots }}</span>
          <span class="kpi-tag available-tag">Listos para Asignar</span>
        </div>

        <div class="kpi-card occupied">
          <span class="kpi-title">Ocupados</span>
          <span class="kpi-value">{{ state.stats().occupiedSpots }}</span>
          <span class="kpi-tag occupied-tag">{{ state.stats().occupancyPercentage }}% de Ocupación</span>
        </div>

        <div class="kpi-card out">
          <span class="kpi-title">Fuera de Servicio</span>
          <span class="kpi-value">{{ state.stats().outOfServiceSpots }}</span>
          <span class="kpi-tag out-tag">Mantenimiento</span>
        </div>
      </div>

      <!-- Controls & Filter Toolbar -->
      <div class="toolbar">
        <div class="filter-group">
          <span class="filter-label">Filtrar por:</span>
          <button
            class="filter-chip"
            [class.active]="state.selectedFilter() === 'ALL'"
            (click)="state.setFilter('ALL')"
          >
            Todos ({{ state.stats().totalSpots }})
          </button>
          <button
            class="filter-chip chip-available"
            [class.active]="state.selectedFilter() === 'Available'"
            (click)="state.setFilter('Available')"
          >
            Disponibles ({{ state.stats().availableSpots }})
          </button>
          <button
            class="filter-chip chip-occupied"
            [class.active]="state.selectedFilter() === 'Occupied'"
            (click)="state.setFilter('Occupied')"
          >
            Ocupados ({{ state.stats().occupiedSpots }})
          </button>
          <button
            class="filter-chip chip-out"
            [class.active]="state.selectedFilter() === 'OutOfService'"
            (click)="state.setFilter('OutOfService')"
          >
            Fuera de Servicio ({{ state.stats().outOfServiceSpots }})
          </button>
        </div>
      </div>

      <!-- 30-Spot Grid -->
      <app-parking-grid></app-parking-grid>

      <!-- Interactive Modals -->
      <app-entry-modal></app-entry-modal>
      <app-checkout-modal></app-checkout-modal>
    </div>
  `,
  styles: [`
    .mfe-container {
      padding: 24px;
      max-width: 1400px;
      margin: 0 auto;
      font-family: 'Plus Jakarta Sans', 'Inter', -apple-system, sans-serif;
    }
    .mfe-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 24px;
      flex-wrap: wrap;
      gap: 16px;
    }
    .brand-pill {
      display: inline-block;
      margin-bottom: 6px;
    }
    .brand-sub {
      background: #EDE9FE;
      color: #5825C6;
      font-size: 0.72rem;
      font-weight: 800;
      letter-spacing: 0.08em;
      padding: 4px 10px;
      border-radius: 9999px;
    }
    .mfe-header h2 {
      margin: 0;
      font-size: 1.6rem;
      font-weight: 800;
      color: #0F172A;
      letter-spacing: -0.02em;
    }
    .subtitle {
      margin: 4px 0 0 0;
      color: #64748B;
      font-size: 0.9rem;
    }
    .concurrency-btn {
      background: linear-gradient(135deg, #6C35DE 0%, #4A1E9E 100%);
      color: #FFFFFF;
      border: none;
      border-radius: 10px;
      padding: 10px 18px;
      font-family: inherit;
      font-weight: 700;
      font-size: 0.85rem;
      cursor: pointer;
      box-shadow: 0 4px 14px rgba(108, 53, 222, 0.35);
      transition: all 0.2s ease;
      display: flex;
      align-items: center;
      gap: 6px;
    }
    .concurrency-btn:hover {
      transform: translateY(-2px);
      box-shadow: 0 6px 18px rgba(108, 53, 222, 0.45);
    }
    .concurrency-alert {
      background: #FAF5FF;
      border: 1.5px solid #C4B5FD;
      color: #4A1E9E;
      padding: 12px 18px;
      border-radius: 12px;
      margin-bottom: 20px;
      display: flex;
      align-items: center;
      gap: 12px;
      animation: slideDown 0.3s ease-out;
      font-size: 0.9rem;
      font-weight: 600;
    }
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 16px;
      margin-bottom: 24px;
    }
    .kpi-card {
      background: #FFFFFF;
      border: 1px solid #E2E8F0;
      border-radius: 14px;
      padding: 18px;
      display: flex;
      flex-direction: column;
      box-shadow: 0 2px 8px rgba(0,0,0,0.03);
    }
    .kpi-title {
      font-size: 0.8rem;
      font-weight: 600;
      color: #64748B;
    }
    .kpi-value {
      font-size: 2rem;
      font-weight: 800;
      color: #0F172A;
      margin: 4px 0;
      line-height: 1.1;
    }
    .kpi-tag {
      font-size: 0.75rem;
      font-weight: 600;
      color: #64748B;
    }
    .available-tag {
      color: #059669;
    }
    .occupied-tag {
      color: #5825C6;
    }
    .out-tag {
      color: #64748B;
    }
    .toolbar {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 16px;
      flex-wrap: wrap;
      gap: 12px;
    }
    .filter-group {
      display: flex;
      align-items: center;
      gap: 8px;
      flex-wrap: wrap;
    }
    .filter-label {
      font-size: 0.825rem;
      font-weight: 600;
      color: #64748B;
      margin-right: 4px;
    }
    .filter-chip {
      background: #FFFFFF;
      border: 1.5px solid #E2E8F0;
      border-radius: 8px;
      padding: 6px 14px;
      font-size: 0.8rem;
      font-weight: 600;
      font-family: inherit;
      cursor: pointer;
      color: #334155;
      transition: all 0.15s ease;
    }
    .filter-chip:hover {
      border-color: #CBD5E1;
      background: #F8FAFC;
    }
    .filter-chip.active {
      background: #6C35DE;
      color: #FFFFFF;
      border-color: #6C35DE;
      box-shadow: 0 2px 8px rgba(108, 53, 222, 0.25);
    }
    .chip-available.active {
      background: #10B981;
      border-color: #10B981;
      box-shadow: 0 2px 8px rgba(16, 185, 129, 0.25);
    }
    .chip-occupied.active {
      background: #4A1E9E;
      border-color: #4A1E9E;
      box-shadow: 0 2px 8px rgba(74, 30, 158, 0.25);
    }
    .chip-out.active {
      background: #64748B;
      border-color: #64748B;
      box-shadow: 0 2px 8px rgba(100, 116, 139, 0.25);
    }
    @keyframes slideDown {
      from { transform: translateY(-10px); opacity: 0; }
      to { transform: translateY(0); opacity: 1; }
    }
  `]
})
export class AppComponent {
  state = inject(ParkingStateService);
}

// src/frontend/domonow-vue-analytics/src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { useAnalyticsStore } from './stores/analyticsStore';
import DemandHeatmap from './components/DemandHeatmap.vue';
import PeakHourForecaster from './components/PeakHourForecaster.vue';
import ActivityFeed from './components/ActivityFeed.vue';
import ActiveAssignmentsTable from './components/ActiveAssignmentsTable.vue';
import CustomDialog from './components/CustomDialog.vue';

const store = useAnalyticsStore();

onMounted(() => {
  store.initCrossMfeListener();
  store.fetchAnalyticsData();
});
</script>

<template>
  <div class="analytics-container">
    <!-- Subproject Visual Header -->
    <header class="mfe-header">
      <div class="header-left">
        <div class="brand-pill">
          <span class="brand-sub">{{ store.t.brandSub }}</span>
        </div>
        <h2>{{ store.t.title }}</h2>
        <p class="subtitle">{{ store.t.subtitle }}</p>
      </div>

      <div class="header-right">
        <div class="date-range-badge">
          <span>{{ store.t.dateRange }}</span>
        </div>
      </div>
    </header>

    <!-- Offline / API Error Strip -->
    <div v-if="store.apiError" class="offline-strip">
      <div class="strip-left">
        <span class="strip-icon">⚠️</span>
        <div class="strip-texts">
          <strong>{{ store.currentLang === 'en' ? 'Backend Service Offline:' : 'Servidor API .NET 10 Fuera de Línea:' }}</strong>
          <span>{{ store.apiError.message }}</span>
        </div>
      </div>
      <button class="strip-btn" @click="store.fetchAnalyticsData()">
        🔄 {{ store.currentLang === 'en' ? 'Re-sync API' : 'Reintentar Sincronización' }}
      </button>
    </div>

    <!-- Top KPI Row -->
    <div class="kpi-grid">
      <div class="kpi-card">
        <span class="kpi-title">{{ store.t.kpiVisitsToday }}</span>
        <span class="kpi-value">{{ store.totalVisitsToday }}</span>
        <span class="kpi-tag positive">{{ store.t.kpiVsAvg }}</span>
      </div>

      <div class="kpi-card">
        <span class="kpi-title">{{ store.t.kpiTurnaround }}</span>
        <span class="kpi-value">{{ Math.floor(store.averageTurnaroundMinutes / 60) }}h {{ store.averageTurnaroundMinutes % 60 }}m</span>
        <span class="kpi-tag">{{ store.t.kpiTurnover }}</span>
      </div>

      <div class="kpi-card">
        <span class="kpi-title">{{ store.t.kpiOccupancyRate }}</span>
        <span class="kpi-value">{{ store.currentOccupancyRate }}%</span>
        <span class="kpi-tag warning">{{ store.t.kpiZoneLabel }}</span>
      </div>

      <div class="kpi-card ml-kpi">
        <span class="kpi-title">{{ store.t.kpiNextPeak }}</span>
        <span class="kpi-value">{{ store.predictedNextHourSurge }}%</span>
        <span class="kpi-tag ml-tag">{{ store.t.kpiProjectionWindow }}</span>
      </div>
    </div>

    <!-- Active Assignments in Visitor Parking (Real .NET 10 API & PostgreSQL) -->
    <ActiveAssignmentsTable />

    <!-- Core Forecasting & Heatmap Components -->
    <DemandHeatmap />
    <PeakHourForecaster />
    <ActivityFeed />

    <!-- Unified DomoNow Custom Dialog -->
    <CustomDialog />
  </div>
</template>

<style scoped>
.analytics-container {
  padding: 24px;
  max-width: 1400px;
  margin: 0 auto;
  font-family: 'Plus Jakarta Sans', 'Inter', -apple-system, sans-serif;
}
.mfe-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 24px;
  flex-wrap: wrap;
  gap: 16px;
}
.brand-pill {
  display: inline-block;
  margin-bottom: 6px;
}
.brand-sub {
  background: #EDE9FE;
  color: #5825C6;
  font-size: 0.72rem;
  font-weight: 800;
  letter-spacing: 0.08em;
  padding: 4px 10px;
  border-radius: 9999px;
}
.mfe-header h2 {
  margin: 0;
  font-size: 1.6rem;
  font-weight: 800;
  color: #0F172A;
  letter-spacing: -0.02em;
}
.subtitle {
  margin: 4px 0 0 0;
  color: #64748B;
  font-size: 0.9rem;
}
.date-range-badge {
  background: #FFFFFF;
  border: 1px solid #CBD5E1;
  padding: 8px 14px;
  border-radius: 10px;
  font-size: 0.825rem;
  font-weight: 600;
  color: #334155;
  box-shadow: 0 1px 4px rgba(0,0,0,0.04);
}
.kpi-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 16px;
  margin-bottom: 24px;
}
.kpi-card {
  background: #FFFFFF;
  border: 1px solid #E2E8F0;
  border-radius: 14px;
  padding: 18px;
  display: flex;
  flex-direction: column;
  box-shadow: 0 2px 8px rgba(0,0,0,0.03);
}
.kpi-title {
  font-size: 0.8rem;
  font-weight: 600;
  color: #64748B;
}
.kpi-value {
  font-size: 2rem;
  font-weight: 800;
  color: #0F172A;
  margin: 4px 0;
  line-height: 1.1;
}
.kpi-tag {
  font-size: 0.75rem;
  font-weight: 600;
  color: #64748B;
}
.kpi-tag.positive {
  color: #10B981;
}
.kpi-tag.warning {
  color: #F59E0B;
}
.ml-kpi {
  border-color: #DDD6FE;
  background: linear-gradient(180deg, #FAF5FF 0%, #FFFFFF 100%);
}
.ml-tag {
  color: #6C35DE;
}
.offline-strip {
  background: #FEF2F2;
  border: 1.5px solid #FCA5A5;
  border-radius: 14px;
  padding: 14px 20px;
  margin-bottom: 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 12px;
  animation: slideDown 0.3s ease-out;
}
.strip-left {
  display: flex;
  align-items: center;
  gap: 10px;
}
.strip-icon {
  font-size: 20px;
}
.strip-texts {
  display: flex;
  flex-direction: column;
  gap: 2px;
  font-size: 0.88rem;
  color: #991B1B;
}
.strip-btn {
  background: #DC2626;
  color: #FFFFFF;
  border: none;
  border-radius: 8px;
  padding: 8px 16px;
  font-size: 0.825rem;
  font-weight: 700;
  cursor: pointer;
  transition: all 0.2s;
}
.strip-btn:hover {
  background: #B91C1C;
}
@keyframes slideDown {
  from { transform: translateY(-10px); opacity: 0; }
  to { transform: translateY(0); opacity: 1; }
}
</style>
